
export enum ClientCommand {
    LOAD_GAME = "LOAD_GAME",
    ACTIVATE_TURN = "ACTIVATE_TURN",
    DEACTIVATE_TURN = "DEACTIVATE_TURN",
    SHOW_CARD = "SHOW_CARD",
    HIDE_CARDS = "HIDE_CARDS",
    UPDATE_SCORE = "UPDATE_SCORE"
}