
export enum ClientCommand {
    LOAD_GAME = "LOAD_GAME",
    ACTIVATE_TURN = "ACTIVATE_TURN",
    DEACTIVATE_TURN = "DEACTIVATE_TURN",
    SHOW_CARD = "SHOW_CARD",
    SHOW_MESSAGE = "SHOW_MESSAGE",
    HIDE_CARDS = "HIDE_CARDS",
    UPDATE_SCORE = "UPDATE_SCORE",
    FINISH_GAME = "FINISH_GAME",
}